name: CI
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      
      # Build
      
      - name: Percy Test
        run: npx @percy/cli snapshot _site/ # or any directory such as public/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Percy Test
        run: npx @percy/cli snapshot _site/ # or any directory such as public/

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
